### ISSUE TITLE
how to write schema for Map<key, value> alike structure?

### ISSUE THREAD

**Issue by naivefun** [jquense/yup#657]
Actually I'm working on JSON schema validator, which is a nested ObjectSchema structure.

I want to validate each value, what's the correct way to write schema?
```yaml
# schema
type: object
properties:
	name: # random keys, cannot use object.shape
		[schema]
	email:
		[schema]
```
